Issue #2954298: Paragraphs actions are rendered as dropdown when there is only one option
thunder/paragraphs_features pull request #11
Opened 2018-03-29 07:38 UTC by ol0lll

2018-04-04 12:44 UTC, mtodor requested changes
We need tests for this feature

2018-04-26 12:11 UTC, dbosen requested changes
A links.menu.yml entry is missing for the settingsform. Currently you have to know the route to change the settings.

2018-05-02 12:59 UTC, mtodor approved these changes

2018-05-02 13:01 UTC, dbosen approved these changes

2018-05-02 13:33 UTC, merged