Issue #3324781: Add split text functionality to CKEditor 5
thunder/paragraphs_features pull request #76
Opened 2023-10-25 14:11 UTC by zibellino

Implementation of the split text (split paragraph) functionality for CKEditor5.
Based on the [ckeditor5_plugin_starter_template](https://git.drupalcode.org/project/ckeditor5_dev/-/tree/1.0.x/ckeditor5_plugin_starter_template), and as such has the same dependencies.

Uses a custom split function instead of [SplitOperation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_operation_splitoperation-SplitOperation.html), and the "Add in-between" button instead of it's own modal.

https://www.drupal.org/project/paragraphs_features/issues/3400542

2023-11-08 10:55 UTC, milkovsky requested changes
The code both looks and works good! There are 2 minor comments.

2023-11-08 10:55 UTC, milkovsky commented on paragraphs_features.ckeditor5.yml
> +      - <div>
missing NL

2023-11-08 10:55 UTC, milkovsky commented on paragraphs_features.libraries.yml
> +      css/split_paragraph.admin.css: {}
missing NL

2023-11-08 10:56 UTC, milkovsky commented
Also please create a d.o. issue for this feature.

2023-11-10 13:43 UTC, milkovsky approved these changes
looks and works good!

2023-11-10 13:43 UTC, milkovsky approved these changes
well done

2023-11-16 13:54 UTC, milkovsky approved these changes

2023-11-16 15:22 UTC, milkovsky approved these changes

2024-04-05 09:27 UTC, ol0lll commented
Closing in favour of #80

2024-04-05 09:27 UTC, closed without merging